apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-configmap
  namespace: bookstore
data:
  DB_HOST: mysql-service
  DB_PORT: '3306'
  DB_NAME: bookstore
  DB_USER: root
  DB_PASSWORD: thien2410vv
  IMAGE_PATH: /usr/share/nginx/html/images/
  MYSQL_ROOT_PASSWORD: thien2410vv
  MYSQL_DATABASE: bookstore
  IMAGE_CONTAINER_PATH: /usr/share/nginx/html/images/
  init.sql: |
    -- MySQL dump 10.13  Distribute 8.0.34, for Win64 (x86_64)
    --
    -- Host: localhost    Database: bookstore
    -- ------------------------------------------------------
    -- Server version   8.0.34

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!50503 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    USE bookstore

    --
    -- Table structure for table `book_details`
    --

    DROP TABLE IF EXISTS `book_details`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `book_details` (
      `id` int NOT NULL AUTO_INCREMENT,
      `dimension` varchar(255) DEFAULT NULL,
      `cover_type` varchar(255) DEFAULT NULL,
      `description` tinytext,
      `number_of_pages` int DEFAULT NULL,
      `publication_date` date DEFAULT NULL,
      `publisher` varchar(255) DEFAULT NULL,
      `publishing_house` varchar(255) DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `book_image`
    --

    DROP TABLE IF EXISTS `book_image`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `book_image` (
      `id` int NOT NULL AUTO_INCREMENT,
      `image_path` tinytext NOT NULL,
      `book_id` int DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FK8coi0vhjgtdmxiauef3r2vc3f` (`book_id`),
      CONSTRAINT `FK8coi0vhjgtdmxiauef3r2vc3f` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `books`
    --

    DROP TABLE IF EXISTS `books`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `books` (
      `id` int NOT NULL AUTO_INCREMENT,
      `current_quantity` int NOT NULL,
      `price` double NOT NULL,
      `sold_quantity` int DEFAULT NULL,
      `title` varchar(255) DEFAULT NULL,
      `book_details_id` int DEFAULT NULL,
      `user_id` int DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      `shop_id` int DEFAULT NULL,
      `author` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `UK_g0yemt6794c54s32263wj5ulf` (`book_details_id`),
      KEY `FKcykkh3hxh89ammmwch0gw5o1s` (`user_id`),
      KEY `FKmfjhptaju03egl87fhelf5wbs` (`shop_id`),
      CONSTRAINT `FKcykkh3hxh89ammmwch0gw5o1s` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
      CONSTRAINT `FKmfjhptaju03egl87fhelf5wbs` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`id`),
      CONSTRAINT `FKpp3n69je2hutyrx5r3fnnaa70` FOREIGN KEY (`book_details_id`) REFERENCES `book_details` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `books_categories`
    --

    DROP TABLE IF EXISTS `books_categories`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `books_categories` (
      `book_id` int NOT NULL,
      `category_id` int NOT NULL,
      PRIMARY KEY (`book_id`,`category_id`),
      KEY `FK4klp9o273ej1ywgmie14rvdx3` (`category_id`),
      CONSTRAINT `FK4klp9o273ej1ywgmie14rvdx3` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`),
      CONSTRAINT `FKmsuoucvyyccli3f6u59co41cq` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `categories`
    --

    DROP TABLE IF EXISTS `categories`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `categories` (
      `id` int NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      `parent_id` int DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    LOCK TABLES `categories` WRITE;
    /*!40000 ALTER TABLE `categories` DISABLE KEYS */;
    INSERT INTO `categories` VALUES (1,'Arts & Photography',NULL,NULL,NULL,NULL,NULL),(2,'Fashion',1,NULL,NULL,NULL,NULL),(3,'Graphic Design',1,NULL,NULL,NULL,NULL),(4,'Business & Money',NULL,NULL,NULL,NULL,NULL),(5,'Economics',4,NULL,NULL,NULL,NULL),(6,'Investing',4,NULL,NULL,NULL,NULL),(7,'Humor & Entertainment',NULL,NULL,NULL,NULL,NULL),(8,'Humor',7,NULL,NULL,NULL,NULL),(9,'Puzzles & Games',7,NULL,NULL,NULL,NULL);
    /*!40000 ALTER TABLE `categories` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `order_items`
    --

    DROP TABLE IF EXISTS `order_items`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `order_items` (
      `id` int NOT NULL AUTO_INCREMENT,
      `quantity` int NOT NULL,
      `book_id` int DEFAULT NULL,
      `order_id` int DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FKi4ptndslo2pyfp9r1x0eulh9g` (`book_id`),
      KEY `FKbioxgbv59vetrxe0ejfubep1w` (`order_id`),
      CONSTRAINT `FKbioxgbv59vetrxe0ejfubep1w` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
      CONSTRAINT `FKi4ptndslo2pyfp9r1x0eulh9g` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `orders`
    --

    DROP TABLE IF EXISTS `orders`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `orders` (
      `id` int NOT NULL AUTO_INCREMENT,
      `delivery_address` varchar(255) DEFAULT NULL,
      `date` date NOT NULL,
      `order_status` varchar(255) NOT NULL,
      `total_price` double NOT NULL,
      `shop_id` int DEFAULT NULL,
      `user_id` int DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      `is_confirm` bit(1) NOT NULL,
      `is_evaluate` bit(1) NOT NULL,
      PRIMARY KEY (`id`),
      KEY `FK21gttsw5evi5bbsvleui69d7r` (`shop_id`),
      KEY `FK32ql8ubntj5uh44ph9659tiih` (`user_id`),
      CONSTRAINT `FK21gttsw5evi5bbsvleui69d7r` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`id`),
      CONSTRAINT `FK32ql8ubntj5uh44ph9659tiih` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `rates`
    --

    DROP TABLE IF EXISTS `rates`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `rates` (
      `book_id` int NOT NULL,
      `user_id` int NOT NULL,
      `rating` int NOT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`book_id`,`user_id`),
      KEY `FKanlgavwqngljux10mtly8qr6f` (`user_id`),
      CONSTRAINT `FK680ef588cndk2bwb5hdkcq1pg` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`),
      CONSTRAINT `FKanlgavwqngljux10mtly8qr6f` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `reviews`
    --

    DROP TABLE IF EXISTS `reviews`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `reviews` (
      `id` int NOT NULL AUTO_INCREMENT,
      `comment` varchar(255) DEFAULT NULL,
      `image` tinytext,
      `book_id` int DEFAULT NULL,
      `user_id` int DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FK6a9k6xvev80se5rreqvuqr7f9` (`book_id`),
      KEY `FKcgy7qjc1r99dp117y9en6lxye` (`user_id`),
      CONSTRAINT `FK6a9k6xvev80se5rreqvuqr7f9` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`),
      CONSTRAINT `FKcgy7qjc1r99dp117y9en6lxye` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `roles`
    --

    DROP TABLE IF EXISTS `roles`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `roles` (
      `id` int NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `UK_ofx66keruapi6vyqpv6f2or37` (`name`)
    ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    LOCK TABLES `roles` WRITE;
    /*!40000 ALTER TABLE `roles` DISABLE KEYS */;
    INSERT INTO `roles` VALUES (1,'ROLE_USER',NULL,NULL,NULL,NULL),(2,'ROLE_SHOP',NULL,NULL,NULL,NULL),(3,'ROLE_ADMIN',NULL,NULL,NULL,NULL);
    /*!40000 ALTER TABLE `roles` ENABLE KEYS */;
    UNLOCK TABLES;
    /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

    --
    -- Table structure for table `shop_details`
    --

    DROP TABLE IF EXISTS `shop_details`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `shop_details` (
      `id` int NOT NULL AUTO_INCREMENT,
      `description` varchar(255) DEFAULT NULL,
      `operating_hours` varchar(255) DEFAULT NULL,
      `return_policy` varchar(255) DEFAULT NULL,
      `shipping_policy` varchar(255) DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `shops`
    --

    DROP TABLE IF EXISTS `shops`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `shops` (
      `id` int NOT NULL AUTO_INCREMENT,
      `contact_email` varchar(255) DEFAULT NULL,
      `contact_phone` varchar(255) DEFAULT NULL,
      `shop_address` varchar(255) DEFAULT NULL,
      `shop_logo_path` tinytext,
      `shop_name` varchar(255) DEFAULT NULL,
      `shop_details_id` int DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `UK_jsb2o70qrgnrv4d8egcfe5rf2` (`shop_details_id`),
      CONSTRAINT `FKgl1bh05w9f8o5rfo7quo0cb5x` FOREIGN KEY (`shop_details_id`) REFERENCES `shop_details` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `users`
    --

    DROP TABLE IF EXISTS `users`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `users` (
      `id` int NOT NULL AUTO_INCREMENT,
      `email` varchar(255) DEFAULT NULL,
      `password` varchar(255) DEFAULT NULL,
      `phone_number` varchar(255) DEFAULT NULL,
      `user_name` varchar(50) DEFAULT NULL,
      `shop_id` int DEFAULT NULL,
      `create_by` varchar(255) DEFAULT NULL,
      `create_date` date DEFAULT NULL,
      `update_by` varchar(255) DEFAULT NULL,
      `update_date` date DEFAULT NULL,
      `social_id` varchar(255) DEFAULT NULL,
      `type` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `UK_gafr9ex7jicsi3o0qognadwhl` (`shop_id`),
      UNIQUE KEY `user_name_UNIQUE` (`user_name`),
      CONSTRAINT `FKbadc51v95q4hmcfflt8g3yfck` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `users_roles`
    --

    DROP TABLE IF EXISTS `users_roles`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `users_roles` (
      `user_id` int NOT NULL,
      `role_id` int NOT NULL,
      PRIMARY KEY (`user_id`,`role_id`),
      KEY `FKj6m8fwv7oqv74fcehir1a9ffy` (`role_id`),
      CONSTRAINT `FK2o0jvgh89lemvvo17cbqvdxaa` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
      CONSTRAINT `FKj6m8fwv7oqv74fcehir1a9ffy` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;
    /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

    -- Dump completed on 2024-01-23 14:33:52